# Generated by Django 4.1.6 on 2023-03-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=-5057745754366621954, max_length=50),
        ),
    ]
