# Generated by Django 4.1.6 on 2023-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='nameuser', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=4405111827860287742, max_length=50),
        ),
    ]
