# Generated by Django 4.1.6 on 2023-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_user_username_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
